name: 'Check Git Signatures'
description: 'Checks if git signatures are as required.'
inputs:
    require_signed_tags:
        description: 'Require all tags to be signed.'
        required: false
        default: true
    require_tag_signing_fpr:
        description: 'Required tags to be signed with a key associated with this primary key FPR'
        required: false
    require_signed_commits:
        description: 'Require all commits to be signed.'
        required: false
        default: false
    require_commit_signing_fpr:
        description: 'Required commits to be signed with a key associated with this primary key FPR'
        required: false
    gpg_import_keys_dir:
        description: 'Dir with a number of exported public keys gpg will import for sig verification.'
        required: false
runs:
    using: "composite"
    steps:
        - run: |
            git config gpg.program gpg2
            git config gpgv.program gpg2
            git fetch origin nightly:refs/remotes/origin/nightly
            ${{ github.action_path }}/script.sh
          shell: bash
