name: Cargo Audit

on:
  # Only merges to master matter.
  pull_request:
    type: [opened, synchronize]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

  schedule:
    - cron: '33 3 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rustonaut/cargo-audit-preloaded/action@v0
      # - uses: actions-rs/audit-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
