name: On new Issue

on:
  issues:
    type: [opened]

jobs:
  assign-me:
    runs-on: ubuntu-latest
    steps:
        #TODO consider replacing with actions/github-scripts
      - name: "Automatically Assign Issues"
        uses: rustonaut/auto-assign-issue@forked
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: rustonaut
