name: On PR WIP check and post WIP checks.
on:
  pull_request:
    type: [opened, reopened, synchronize, edited]

jobs:
  wip-check-and-post-wip-checks:
    runs-on: ubuntu-latest
    # TODO Use latest stable or night
    # TODO Only if title doesn't start wit WIP:
    steps:
      - uses: actions/github-script@v3
        id: wip-check
        with:
          script: |
            const pr = context.payload.pull_request;
            const issue_resp = await github.issues.get(pr);
            const issue = issue_resp.data;
            if (issue.title.startsWith("WIP")) {
                throw Error("Can not merge WIP pull requests.")
            }

      - uses: actions/checkout@v1

      - uses: ./.github/actions/verify-signatures
        with:
          require_signed_commits: false
          require_signed_tags: true
          require_tag_signing_fpr: ${{ secrets.TagSigningFpr }}
